# Generated by Django 4.2.11 on 2024-04-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproducts', '0003_alter_author_author_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
