# Generated by Django 4.2.11 on 2024-04-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyproducts', '0005_editions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editions',
            old_name='Edition_description',
            new_name='edition_description',
        ),
    ]
