# Generated by Django 4.2.11 on 2024-04-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproducts', '0006_rename_edition_description_editions_edition_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='editions',
            name='publication_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='editions',
            name='publisher',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
