# Generated by Django 4.2.11 on 2024-04-11 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyproducts', '0007_editions_publication_year_editions_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variant',
            name='edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buyproducts.editions'),
        ),
    ]
