# Generated by Django 5.0.4 on 2024-04-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproducts', '0009_alter_productreview_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variant',
            name='qty_per_person',
            field=models.IntegerField(default=5),
        ),
    ]
