# Generated by Django 5.0.4 on 2024-05-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproducts', '0013_category_max_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
