# Generated by Django 5.0.4 on 2024-04-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Return processing', 'Return processing'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Return requested', 'Return requested'), ('Order confirmed', 'Order confirmed'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped')], default='Order confirmed', max_length=50),
        ),
    ]
