# Generated by Django 5.0.4 on 2024-04-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Out for delivery', 'Out for delivery'), ('Order confirmed', 'Order confirmed'), ('Return requested', 'Return requested'), ('Delivered', 'Delivered'), ('Return processing', 'Return processing'), ('Returned', 'Returned'), ('Shipped', 'Shipped')], default='Order confirmed', max_length=50),
        ),
    ]
