# Generated by Django 5.0.4 on 2024-04-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_coupon_amount_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Return processing', 'Return processing'), ('Cancelled', 'Cancelled'), ('Return requested', 'Return requested'), ('Returned', 'Returned'), ('Out for delivery', 'Out for delivery')], default='Order confirmed', max_length=50),
        ),
    ]
