# Generated by Django 5.0.4 on 2024-04-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Order confirmed', 'Order confirmed'), ('Return processing', 'Return processing'), ('Returned', 'Returned'), ('Return requested', 'Return requested'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='Order confirmed', max_length=50),
        ),
    ]
