# Generated by Django 5.0.4 on 2024-04-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Return requested', 'Return requested'), ('Order confirmed', 'Order confirmed'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Return processing', 'Return processing'), ('Delivered', 'Delivered')], default='Order confirmed', max_length=50),
        ),
    ]
