# Generated by Django 5.0.4 on 2024-04-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Order confirmed', 'Order confirmed'), ('Delivered', 'Delivered'), ('Return requested', 'Return requested'), ('Out for delivery', 'Out for delivery'), ('Shipped', 'Shipped'), ('Return processing', 'Return processing')], default='Order confirmed', max_length=50),
        ),
    ]
