# Generated by Django 5.0.4 on 2024-04-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Order confirmed', 'Order confirmed'), ('Out for delivery', 'Out for delivery'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Return requested', 'Return requested'), ('Return processing', 'Return processing')], default='Order confirmed', max_length=50),
        ),
    ]
