# Generated by Django 5.0.4 on 2024-04-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Order confirmed', 'Order confirmed'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled'), ('Return requested', 'Return requested'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Return processing', 'Return processing')], default='Order confirmed', max_length=50),
        ),
    ]
