# Generated by Django 5.0.4 on 2024-04-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Order confirmed', 'Order confirmed'), ('Returned', 'Returned'), ('Return processing', 'Return processing'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Return requested', 'Return requested'), ('Cancelled', 'Cancelled')], default='Order confirmed', max_length=50),
        ),
    ]
