# Generated by Django 5.0.4 on 2024-04-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Return requested', 'Return requested'), ('Out for delivery', 'Out for delivery'), ('Shipped', 'Shipped'), ('Order confirmed', 'Order confirmed'), ('Return processing', 'Return processing'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Order confirmed', max_length=50),
        ),
    ]
