# Generated by Django 5.0.4 on 2024-04-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Return requested', 'Return requested'), ('Out for delivery', 'Out for delivery'), ('Cancelled', 'Cancelled'), ('Return processing', 'Return processing'), ('Delivered', 'Delivered'), ('Order confirmed', 'Order confirmed')], default='Order confirmed', max_length=50),
        ),
    ]
