# Generated by Django 5.0.4 on 2024-05-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_order_category_amount_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Returned', 'Returned'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Return processing', 'Return processing'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Return requested', 'Return requested')], default='Order confirmed', max_length=50),
        ),
    ]
