# Generated by Django 5.0.4 on 2024-05-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Return requested', 'Return requested'), ('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Return processing', 'Return processing'), ('Order confirmed', 'Order confirmed'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Order confirmed', max_length=50),
        ),
    ]
