# Generated by Django 5.0.4 on 2024-05-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Return requested', 'Return requested'), ('Out for delivery', 'Out for delivery'), ('Returned', 'Returned'), ('Return processing', 'Return processing'), ('Shipped', 'Shipped')], default='Order confirmed', max_length=50),
        ),
    ]
