# Generated by Django 5.0.4 on 2024-05-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_order_order_address_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Return processing', 'Return processing'), ('Returned', 'Returned'), ('Delivered', 'Delivered'), ('Order confirmed', 'Order confirmed'), ('Cancelled', 'Cancelled'), ('Out for delivery', 'Out for delivery'), ('Return requested', 'Return requested')], default='Order confirmed', max_length=50),
        ),
    ]
