# Generated by Django 5.0.4 on 2024-05-17 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_alter_order_order_address_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Order confirmed', 'Order confirmed'), ('Returned', 'Returned'), ('Return requested', 'Return requested'), ('Return processing', 'Return processing')], default='Order confirmed', max_length=50),
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('alternative_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('town', models.CharField(max_length=150)),
                ('zip_code', models.IntegerField()),
                ('nearby_location', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
