# Generated by Django 5.0.4 on 2024-05-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_alter_order_status_orderaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Return processing', 'Return processing'), ('Out for delivery', 'Out for delivery'), ('Return requested', 'Return requested'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Order confirmed', 'Order confirmed'), ('Returned', 'Returned'), ('Shipped', 'Shipped')], default='Order confirmed', max_length=50),
        ),
    ]
