# Generated by Django 5.0.4 on 2024-05-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_remove_order_order_address_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Return processing', 'Return processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Out for delivery', 'Out for delivery'), ('Order confirmed', 'Order confirmed'), ('Return requested', 'Return requested'), ('Shipped', 'Shipped'), ('Returned', 'Returned')], default='Order confirmed', max_length=50),
        ),
    ]
