# Generated by Django 5.0.4 on 2024-05-17 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.orderaddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Order confirmed', 'Order confirmed'), ('Return requested', 'Return requested'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Shipped', 'Shipped'), ('Return processing', 'Return processing'), ('Out for delivery', 'Out for delivery')], default='Order confirmed', max_length=50),
        ),
    ]
