# Generated by Django 5.0.4 on 2024-04-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_forgotpassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
