# Generated by Django 4.2.11 on 2024-04-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_delete_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['id'], 'verbose_name': 'CustomUser'},
        ),
    ]
