# Generated by Django 5.0.4 on 2024-04-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_customuser_referral_code_customuser_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dummy',
            field=models.CharField(default='yes', max_length=250),
        ),
    ]
