# Generated by Django 5.0.4 on 2024-04-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_customuser_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dummy',
        ),
    ]
