# Generated by Django 5.0.4 on 2024-04-19 06:01

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=15)),
                ('min_amount', models.PositiveBigIntegerField()),
                ('off_percent', models.PositiveBigIntegerField()),
                ('max_discount', models.PositiveBigIntegerField()),
                ('coupon_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(validators=[cart.models.validate_expiry_date])),
            ],
        ),
    ]
